# Generated by Django 2.2.10 on 2020-03-02 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200302_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id_projet',
        ),
        migrations.AddField(
            model_name='task',
            name='id_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
            preserve_default=False,
        ),
    ]
