# Generated by Django 2.2.10 on 2020-03-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200303_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processing',
            name='id_user_group',
        ),
        migrations.AddField(
            model_name='processing',
            name='id_user_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Task'),
            preserve_default=False,
        ),
    ]
