# Generated by Django 2.2.10 on 2020-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=128, unique=True)),
                ('lastname', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('group', models.DecimalField(decimal_places=0, max_digits=10000)),
            ],
        ),
    ]
