# Generated by Django 2.2.10 on 2020-02-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=245, unique=True),
            preserve_default=False,
        ),
    ]
