# Generated by Django 2.2.10 on 2020-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkpassword',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
