# Generated by Django 2.2.10 on 2020-02-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200229_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGroup', models.CharField(max_length=42, unique=True)),
                ('idProfile', models.ForeignKey(db_column='idemployee', on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
