# Generated by Django 2.2.10 on 2020-02-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200225_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='projet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Projet'),
            preserve_default=False,
        ),
    ]
