# Generated by Django 2.2.10 on 2020-03-01 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ending_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name_projet', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('group_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=128)),
                ('discription_task', models.TextField(max_length=500)),
                ('task_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('id_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Projet')),
            ],
        ),
    ]
