# Generated by Django 2.2.10 on 2020-02-25 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_worker_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projet',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
